### PR TITLE
My version of the app. A GUI version.

### PR DESCRIPTION
**Pull request by codywd**

### CODE REVIEW

**Comment by codywd** [comment]
Raindolf?

**Comment by nasowah** [comment]
Raindolf / Codywd,

Can we have all the new inputs merged into the raindolf/master ?

~
Stephen

**Comment by codywd** [comment]
I don't see any issue with that 

—

**Comment by codywd** [comment]
I will be removing my repository soon as part of cleaning up my github. Hopefully this gets merged soon

**Comment by nasowah** [comment]
I think this is a nice piece for intro tutorials and a project that can
be developed.

@Raindolf, where are you ?

Regards,
Stephen N. A. Sowah
niiadjeisowah (Gtalk)
nii.adjei.sowah (Skype)
@niiadjeisowah (twitter)
+233279506045 | +233243048334 (Gh)

**Comment by nasowah** [comment]
Hello Raindolf,

Pls see discussion bellow.

Regards,
Stephen N. A. Sowah
niiadjeisowah (Gtalk)
nii.adjei.sowah (Skype)
@niiadjeisowah (twitter)
+233279506045 | +233243048334 (Gh)

**Comment by raindolf** [comment]
Thanks so much @nasowah for the reminder, i have merged all the new inputs into Raindolf/Team-Oasis Thanks and Keep me informed.

**Comment by nasowah** [comment]
@Cody, whats your handle on twitter ? will like to follow you on there.

Regards,
Stephen N. A. Sowah
nii.adjei.sowah (Skype)
@niiadjeisowah (twitter)

**Comment by codywd** [comment]
@nasowah: it's dostalcody

**Pull request merged**
